name: ECS Creation or Deletion
run-name: ${{ github.actor }} is creating or destroying ECS on GitHub Actions 🚀
on:
  workflow_dispatch:
    inputs:
        target_env:
            type: environment
            description: Select the environment to create or destroy
        action:
            type: choice
            options:
                - create
                - destroy
            description: Select the action, whether to create or destroy ECS cluster

jobs:
    pre-action-step:
        runs-on: ubuntu-latest
    
        steps:
        - uses: actions/checkout@v2
    
        - name: print environment and action
          run: | 
            echo "env selected is ${{ inputs.target_env }}"
            echo "action selected is ${{ inputs.action }}"

    create-or-delete-ecs-cluster:
        needs: [pre-action-step]
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Terraform init
          run: terraform init

        - name: Terraform workspace list
          run: terraform workspace list

        - name: Terraform workspace new environment and select
          run: |
            terraform workspace select ${{ github.event.inputs.target_env }} || terraform workspace new ${{ github.event.inputs.target_env }}
            terraform workspace list

        - name: Terraform apply or destroy
          run: |
            if [ "${{ github.event.inputs.action }}" = "create" ]; then
              terraform plan -var-file=${{ github.event.inputs.target_env }}.tfvars
              terraform apply -var-file=${{ github.event.inputs.target_env }}.tfvars --auto-approve
            elif [ "${{ github.event.inputs.action }}" = "destroy" ]; then
              terraform destroy -var-file=${{ github.event.inputs.target_env }}.tfvars -auto-approve
            fi

    summary:
        needs: [create-or-delete-ecs-cluster]
        runs-on: ubuntu-latest
        steps:
            - name: Adding markdown
              run: |
                echo '## 🚀 Preparing Summary 🚀' >> $GITHUB_STEP_SUMMARY
                echo '### Action ran: ${{ inputs.action }}'  >> $GITHUB_STEP_SUMMARY
                echo '### Environment chosen: ${{ inputs.target_env }}'  >> $GITHUB_STEP_SUMMARY
                echo '### Outcome: Successful 🚀'  >> $GITHUB_STEP_SUMMARY
